-- LUAport -- file upload receiver.
--
-- Pairs with tools/upload.py. Sent to the console's Lua loader on TCP 9026 by
-- the uploader itself; it is NOT a payload and NOT generated by tools/mklua.py,
-- so it carries no @@JIT_SIZE@@ and is used verbatim.
--
-- ==========================================================================
-- WHAT THIS IS FOR
-- ==========================================================================
-- Getting a USER-SUPPLIED file into the console sandbox without embedding it in
-- anything. The M3 use is a GBA BIOS:
--
--     make m3-upload-bios PS5_IP=<addr> BIOS=<path to gba_bios.bin>
--
-- NO BIOS IS EMBEDDED ANYWHERE IN LUAport -- not in the image, not in a
-- delivery script, not in this file. gpsp/bios_data.S stays excluded from every
-- build for the same reason (and because its open_gba_bios_rom symbol is a
-- check_forbidden.py LIBRETRO_PATTERNS entry, so linking it would force an
-- allowlist widening).
--
-- Ported from LuaPSX/lua/upload_resume.lua. LuaPSX/ is read-only reference and
-- its copy still works identically; this is an additive LUAport-owned file.
--
-- ==========================================================================
-- WIRE FORMAT
-- ==========================================================================
--     in   u16 path_len (LE), u16 flags (LE), path bytes
--     out  'K', then u64 little-endian current file size
--     in   file bytes from that offset until EOF
--
--     flags bit 0 (0x0001) = open with O_TRUNC
--
-- THE FLAGS WORD IS THE ONE DELIBERATE CHANGE FROM LuaPSX, which was
-- resume-only. Resume-only is right for the ~1GB disc images it was built for,
-- but it is WRONG as a default for a 16KB BIOS: replacing a BIOS with a
-- DIFFERENT one of the same length would silently do nothing, because the
-- sender sees "16384 bytes already present" and stops. The user would keep
-- running their old BIOS while being told the upload succeeded.
--
-- tools/upload.py therefore defaults to the truncate bit and offers --resume
-- for the large-ROM case M4 will need. Both ends of this protocol are LUAport's
-- own, so the change is self-contained.
--
-- Ping-class: writes one file and returns. The loader survives, so the console
-- does not need a relaunch between the upload and the M3 payload -- though
-- relaunching anyway is recommended, because every script sent consumes JIT
-- mappings and the M3 payload needs two of them.

init_dlsym()

local PC_IP, LOG_PORT = "auto", 9027

local function htons(p) return ((p << 8) | (p >> 8)) & 0xFFFF end
local function inet_addr(s)
    local a,b,c,d = s:match("(%d+)%.(%d+)%.(%d+)%.(%d+)")
    return (d << 24) | (c << 16) | (b << 8) | a
end

-- Same self-configuring log target as the payload: derive the subnet from our
-- own address rather than baking in one network. Wrapped, because a failure
-- here must not take down an upload that would otherwise succeed.
if PC_IP == "auto" then
    local fallback = "255.255.255.255"
    local ok, own = pcall(function() return tostring(get_current_ip() or "") end)
    PC_IP = fallback
    if ok then
        local a, b, c = own:match("(%d+)%.(%d+)%.(%d+)%.%d+")
        if a and tonumber(a) > 0 and tonumber(a) ~= 127 then
            PC_IP = a .. "." .. b .. "." .. c .. ".255"
        end
    end
end

local lsa = malloc(16)
for i = 0, 15 do write8(lsa + i, 0) end
write8(lsa+0,16); write8(lsa+1,2)
write16(lsa+2, htons(LOG_PORT)); write32(lsa+4, inet_addr(PC_IP))
local lsock = create_socket(AF_INET, SOCK_DGRAM, 0)
if lsock >= 0 then
    local en = malloc(4); write32(en, 1)
    syscall.setsockopt(lsock, 0xffff, 0x0020, en, 4)   -- SO_BROADCAST
end
local function log(m) if lsock >= 0 then syscall.sendto(lsock, m.."\n", #m+1, 0, lsa, 16) end end

log("=== LUAport UPLOAD (logging to " .. PC_IP .. ")")

-- FreeBSD fcntl.h values -- the PS5 kernel is FreeBSD-derived and the Linux
-- numbers are different. O_TRUNC is 0x400, not 0x200 (which is O_CREAT).
local O_WRONLY, O_CREAT, O_TRUNC = 1, 0x200, 0x400
local SEEK_SET, SEEK_END = 0, 2

local sa = malloc(16)
for i = 0, 15 do write8(sa + i, 0) end
write8(sa+0,16); write8(sa+1,2)

local srv = create_socket(AF_INET, SOCK_STREAM, 0)
if srv < 0 then log("create_socket failed"); return end

local en = malloc(4); write32(en, 1)
-- SO_REUSEADDR only. SO_REUSEPORT would let a leaked listener from an earlier
-- script share the port and steal the incoming connection, which hangs this
-- accept() and wedges the loader.
syscall.setsockopt(srv, SOL_SOCKET, 0x0004, en, 4)     -- SO_REUSEADDR

-- Walk a range, exactly as the payload loader does. A script that dies after
-- bind() leaves its listener behind for the rest of the game session, so a
-- fixed port would mean one crash costs a relaunch. tools/upload.py walks the
-- same range and identifies the live receiver by the ACK byte below.
local PORT_LO, PORT_HI = 9028, 9045
local bound = -1
for p = PORT_LO, PORT_HI do
    write16(sa+2, htons(p))
    write32(sa+4, 0)
    if syscall.bind(srv, sa, 16) == 0 then bound = p break end
    log(string.format("bind %d in use, trying next", p))
end
if bound < 0 then log("no free port -- relaunch to clear leaked listeners"); syscall.close(srv); return end

syscall.listen(srv, 1)
log(string.format("waiting on TCP %d (30s timeout)", bound))

-- Timeout, never a bare accept(): a blocking accept that never fires wedges the
-- Luac0re loader and costs a game relaunch.
--
-- fcntl + retry, NOT poll(): syscall.poll is absent from Luac0re's table, so
-- calling it is a nil-call that kills the script with no log output.
local F_SETFL, O_NONBLOCK = 4, 0x0004
syscall.fcntl(srv, F_SETFL, O_NONBLOCK)

local function ok(v) return v ~= nil and v >= 0 and v < 0x80000000 end

-- struct timespec is { time_t tv_sec; long tv_nsec } -- both 8 bytes on this
-- ABI, so these must be 64-bit writes. A 32-bit write leaves the upper half of
-- tv_sec holding whatever malloc returned, which can be a garbage sleep.
local ts = malloc(16)
write64(ts, 0); write64(ts+8, 100000000)               -- 100ms
local cli = -1
for _ = 1, 300 do
    cli = syscall.accept(srv, sa, en)
    if ok(cli) then break end
    syscall.nanosleep(ts, 0)
end
if not ok(cli) then log("accept timed out"); syscall.close(srv); return end
-- Accepted socket must be blocking, or read() returns EAGAIN and the file
-- arrives truncated.
syscall.fcntl(cli, F_SETFL, 0)

local CHUNK = 262144
local buf = malloc(CHUNK)

local function read_exact(fd, dest, want)
    local got = 0
    while got < want do
        local n = syscall.read(fd, dest + got, want - got)
        if n == nil or n <= 0 then return got end
        got = got + n
    end
    return got
end

local function bail(msg, fd)
    log(msg)
    if fd then syscall.close(fd) end
    syscall.close(cli); syscall.close(srv)
end

-- Header: u16 path_len, u16 flags.
if read_exact(cli, buf, 4) ~= 4 then
    bail("short header"); return
end
local plen  = read8(buf)     | (read8(buf + 1) << 8)
local flags = read8(buf + 2) | (read8(buf + 3) << 8)
if plen == 0 or plen > 400 then
    bail("bad path length " .. tostring(plen)); return
end
if read_exact(cli, buf, plen) ~= plen then
    bail("short path"); return
end
local path = ""
for i = 0, plen - 1 do path = path .. string.char(read8(buf + i)) end
log(string.format("path: %s (flags 0x%X)", path, flags))

local pbuf = malloc(512)
for i = 0, 511 do write8(pbuf + i, 0) end
write_string(pbuf, path)

-- Create the parent directory if the destination is nested. /temp0 needs
-- nothing, but the FALLBACK candidate /savedata0/bios/gba_bios.bin lives one
-- level down and the directory may not exist yet. Failure is IGNORED on
-- purpose: it usually means "already exists", and if the directory genuinely
-- cannot be made, the open below reports it with a better message. Wrapped in
-- pcall because syscall.mkdir is not guaranteed to be in Luac0re's table.
local dir = path:match("^(.*)/[^/]+$")
if dir and #dir > 0 and dir:match("^/[^/]+/") then
    pcall(function()
        local dbuf = malloc(512)
        for i = 0, 511 do write8(dbuf + i, 0) end
        write_string(dbuf, dir)
        local r = syscall.mkdir(dbuf, 0x1FF)
        log(string.format("mkdir %s -> %s", dir, tostring(r)))
    end)
end

-- O_TRUNC only when the sender asked for it. Without it, whatever is already
-- there is kept and appended to, which is what makes a dropped transfer
-- resumable.
local oflags = O_WRONLY | O_CREAT
if (flags & 0x1) ~= 0 then
    oflags = oflags | O_TRUNC
    log("replacing (O_TRUNC)")
else
    log("resuming (no O_TRUNC)")
end

local fd = syscall.open(pbuf, oflags, 0x1FF)
log("open -> " .. tostring(fd))
if fd == nil or fd < 0 then
    bail("cannot open file -- is the mount present and writable?"); return
end

-- After O_TRUNC this is 0; without it, it is where the last attempt stopped.
local have = syscall.lseek(fd, 0, SEEK_END)
if have == nil or have < 0 then have = 0 end
log(string.format("already have %d bytes, continuing there", have))

-- 'K' then the offset, so the sender knows where to continue from. Only a
-- RUNNING script sends this byte: a listener leaked by a dead script accepts
-- and buffers without complaint, then resets part-way through, so this ACK is
-- the sender's only reliable way to find the live receiver.
write8(buf, 75)
for i = 0, 7 do write8(buf + 1 + i, (have >> (i * 8)) & 0xFF) end
syscall.write(cli, buf, 9)

local written = have
local next_report = have + 1048576
while true do
    local n = syscall.read(cli, buf, CHUNK)
    if n == nil or n <= 0 then break end
    local off = 0
    while off < n do
        local w = syscall.write(fd, buf + off, n - off)
        if w == nil or w <= 0 then
            log(string.format("write failed at %d (ret %s) -- disk full?",
                              written, tostring(w)))
            syscall.close(fd); syscall.close(cli); syscall.close(srv); return
        end
        off = off + w
        written = written + w
    end
    if written >= next_report then
        log(string.format("  %d bytes written", written))
        next_report = next_report + 1048576
    end
end

syscall.close(fd)
syscall.close(cli)
syscall.close(srv)
log(string.format("DONE: %s, %d bytes", path, written))
